version: '3.8'

services:
  web:
    image: ghcr.io/turbocheetah/latency-monitor:master
    container_name: latency-monitor-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - TARGETS=1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INFLUXDB_V2_URL=http://influx:8086
      - INFLUXDB_V2_ORG=latency-monitor
      - INFLUXDB_V2_TOKEN=change-me
      - INFLUXDB_BUCKET=latency-monitor

  worker:
    image: ghcr.io/turbocheetah/latency-monitor:master
    container_name: latency-monitor-worker
    restart: unless-stopped
    command: celery -A latency_monitor.latency_monitor.celery worker -B --loglevel=info
    depends_on:
      - redis
    environment:
      - TARGETS=1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INFLUXDB_V2_URL=http://influx:8086
      - INFLUXDB_V2_ORG=latency-monitor
      - INFLUXDB_V2_TOKEN=change-me
      - INFLUXDB_BUCKET=latency-monitor

  redis:
    image: redis:alpine
    container_name: latency-monitor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisData:/data

  influx:
    image: influxdb:2.7-alpine
    container_name: latency-monitor-influx
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=latency-monitor
      - DOCKER_INFLUXDB_INIT_PASSWORD=change-me
      - DOCKER_INFLUXDB_INIT_ORG=latency-monitor
      - DOCKER_INFLUXDB_INIT_BUCKET=latency-monitor
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=change-me
    volumes:
      - influxdbData:/var/lib/influxdb2

volumes:
  redisData:
  influxdbData:


networks:
  default:
    name: latency-monitor
    driver: bridge
